version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: prisma_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: toy_sales
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toy_sales_api
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/toy_sales
    command: sh -c "sleep 5 && npx prisma migrate deploy && npm run start:prod"
    ports:
      - "3000:3000"
    volumes:
      - .:/app

volumes:
  postgres_data:
